server.port = 9001
spring.rabbitmq.addresses = localhost:5672


# RabbitMQ Configuration
spring.rabbitmq.host=rabbit
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.virtual-host=/


spring.rabbitmq.queue = measure.queue
spring.rabbitmq.exchange = measure.exchange
spring.rabbitmq.routingkey = measure.routingkey

# Other Database Configurations
database.ip = ${DB_IP:consumer-container}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:postgres}
database.password = ${DB_PASSWORD:root}
database.name = ${DB_DBNAME:Measure}

spring.datasource.url = ${db-url:jdbc:postgresql://monitoring-db-container:5432/Measure}
#spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true

server.tomcat.threads.max = 1

# Logging Configurations

# Embedded Tomcat Configurations
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

jwt.key=ggfdghfdsghsdfjhaejeajaejrejearjearjearjaejda
jwt.issuer=fabrit
jwt.audience=my-other-service


